name: Upload Videos to YouTube

on:
  schedule:
    - cron: '0 9,21 * * *'  # Run at 9 AM and 9 PM UTC daily
  workflow_dispatch:  # Allows manual trigger as well

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up credentials file
      run: echo "${{ secrets.CLIENT_SECRETS_JSON }}" > credentials.json

    - name: Download Dropbox videos
      run: |
        mkdir -p ./downloads
        python download_videos.py  # Assuming a separate Python script for downloading

    - name: Upload videos to YouTube
      run: |
        python upload_videos.py  # Assuming this script uploads videos

    - name: Clean up uploaded video log
      run: |
        echo "Cleaning up uploaded videos log..."
        rm uploaded_videos.log  # Clean up old log if needed

