name: Upload Videos to YouTube

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt for dependencies

    - name: Run script to upload videos
      env:
        CLIENT_SECRETS_FILE_PATH: ${{ secrets.CLIENT_SECRETS_FILE_PATH }}
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      run: python your_script.py  # Replace with the actual script name
